### ISSUE TITLE
Project Plan 09/17 - 10/01

### ISSUE THREAD

**Issue by jgy4** [nickeubank/mtv_viacom_capstone#6]
Hello everyone! This week in our Capstone class we were encouraged to use a more formal short-term task management system. We are hoping to use Github to manage our tasks more formally and share things with our mentors. 

*I believe Dapo & Pranav can add tasks for themselves by editing this issue*

- [x] Clone repository and upload data sources into a Data folder. @jgy4 @dapoade @PranavM98 
- [x] Create more concrete long-term timeline by revisiting Backwards Design @jgy4 @dapoade @PranavM98 
- [x] For 2020 polling data: How many states have polling places reported? How many states have early voting and drop-boxes reported? @jgy4
- [x] For 2020 polling data: Geo-code all polling place addresses @jgy4 
- [x] For 2020 polling data: Initial data quality analysis (search for missing data, other problems, etc.) @jgy4 
- [x] Geo code polling place data from 2012 - 2018 (only 30 of 50 states available) @dapoade 
- [x] Extract College Polygon Data @PranavM98 
- [ ] Find polling place data for 20 missing states above ^ @dapoade 
- [x] Generate a list of types of colleges (HBCU, MSI, PWI) @dapoade
