### ISSUE TITLE
Follow-Up After 11/23 MTV Meeting

### ISSUE THREAD

**Issue by jgy4** [nickeubank/mtv_viacom_capstone#65]
Hi @nickeubank @adrianefresh 

We had a discussion after our meeting with you all and Vaughan to sort through priorities, tasks, and our final report. We'd love your feedback on these!

**Tasks From Today (i.e. requests from Vaughan)**
- [x] Run the early voting data through the Google API to obtain centroid distances and travel times @PranavM98 
- [x] Send Vaughan a list of schools in AZ, TX, GA, NC, FL with polling places over a mile away (MSI, Public) @jgy4 
- [x] Add on/off campus differentiation and school counts to Tableau, send screenshots @dapoade 

**Tasks for Nov. 30th Meeting & Dec. 3rd Final Report**
- [ ] 2020 Election Day Data comparison (sjoin nearest) Safegraph vs. CPI vs. Ballot Ready @jgy4 
- [ ] 2020 Early Voting VIP vs. Ballot Ready comparison @jgy4 
- [x] Look into null/missing distances for 2020 Election Day and 2020 EV @PranavM98 
- [x] Look into null values for Institution Type @dapoade 
- [x] Schedule Meeting with +1 Team @dapoade 
- [x] Adding region labels to '30_campuses_w_dist_to_nearest_pp.geojson' @PranavM98 
- [x] Finding data/drafting an urban/rural differentiation @jgy4 

**Proposed Final Report Outline**
- Introduction 
1. Context of our project
2. Purpose of our project
- Data - For each section we will discuss the source, cleaning, issues/challenges, resolutions, and next steps.
1. Campus Polygons
2. Polling Places
3. Early Voting
- Analysis - For each section we will discuss cuts by MSI Type, Public/Private, 2 Year/4 Year, State/Region, and Urban/Rural.
1. 2020 Early Voting
2. 2020 Election Day
- Conclusion
